MCU = RP2040
BOOTLOADER = rp2040

WS2812_DRIVER = vendor

RGBLIGHT_ENABLE = yes

RAW_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
SEND_STRING_ENABLE = yes